luchy_number:
    path: /lucky
    controller: App\Controller\LuckyController::index

user_list:
  path:     /users
  controller: App\Controller\UserController::list

user_show:
  path:     /user/{id}
  controller: App\Controller\UserController::show
  requirements:
    id: '\d+'